seed = 0
parent_dir = "exp/flnet_all/ddpm_tune_best"
real_data_path = "/data/qgong/data/FLNET"
model_type = "mlp"
num_numerical_features = 76
device = "cuda:2"

[model_params]
num_classes = 11
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    1024,
    256,
    256,
    256,
    256,
    512,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"

[train.main]
steps = 50000
lr = 0.0017214650447494237
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 20000
batch_size = 1024
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
